---
title: "01_load"
format: html
editor: visual
---

## Loading data

```{r}
# Loading the data
path_gene = "../data/_raw/GSE151243_Raw_gene_counts_matrix.txt"
path_meta = "../data/_raw/GSE151243_series_matrix.txt"
gene_table <- read.table(path_gene, header = TRUE)
meta_table <- read.table(path_meta, skip = 33, fill = TRUE, header = TRUE)
```

```{r}
# output: FALSE
library(tidyverse)
library(janitor)
```

```{r}
# output: FALSE
# Pivoting the table and renaming the columns
meta_table <- meta_table |>
  t() |>
    as.data.frame()
colnames(meta_table) <- gsub('!', '', meta_table[1,])
meta_table <- meta_table[-1,]
```

```{r}
# Selecting and renaming the columns we are interested in
meta_table <- meta_table |>
  clean_names() |>
  rownames_to_column(var = "Sample") |>
  select(
    c(
    Sample, 
    sample_characteristics_ch1,
    sample_characteristics_ch1_2,
    sample_characteristics_ch1_3,
    sample_characteristics_ch1_4,
    sample_characteristics_ch1_5,
    sample_characteristics_ch1_6,
    sample_characteristics_ch1_7,
    sample_characteristics_ch1_8)
  ) |>
  rename(
    all_of(c(Tissue = "sample_characteristics_ch1",
    Tissue_type = "sample_characteristics_ch1_2",
    Patient_id = "sample_characteristics_ch1_3",
    Age = "sample_characteristics_ch1_4", 
    Gender = "sample_characteristics_ch1_5",
    Race = "sample_characteristics_ch1_6",
    Smoker = "sample_characteristics_ch1_7",
    BMI = "sample_characteristics_ch1_8"))
  )
```

```{r}
# Tidy columns (with no prefixes)
meta_table <- meta_table |>
  mutate(
    Sample = str_split_i(Sample, pattern="_", 2),
    Tissue = gsub("tissue: ", "", Tissue),
    Tissue_type = gsub("tissue_type: ", "", Tissue_type),
    Patient_id = gsub("patient_id: ", "", Patient_id),
    Age = gsub("age: ", "", Age),
    Gender = gsub("gender: ", "", Gender),
    Race = gsub("race: ", "", Race),
    Smoker= gsub("smoker: ", "", Smoker),
    BMI= gsub("bmi: ", "", BMI),
  )
```

```{r}
# Same operations we want genes as columns
gene_table <- gene_table |>
  t() |>
    as.data.frame()
colnames(gene_table) <- gene_table[1,]
gene_table <- gene_table[-1,]
```

```{r}
# We change the Sample id and put it as a column
gene_table <- gene_table |>
  rownames_to_column(var = "Sample") |>
  mutate(
    Sample = str_split_i(Sample, pattern="_", 2)
  )
```

```{r}
# We join on patient ID
final_table <- meta_table |>
  left_join(
    gene_table,
    by = "Sample"
  )
    
```

```{r}
# We save the corrected data frames at the end of this code
write_tsv(final_table, file = "../data/meta_gene_table.tsv")
```
