---
title: "02_dat_clean"
format: html
editor: visual
---

```{r}
# output: FALSE
library(tidyverse)
```

```{r}
# Loading the created dataset
meta_gene_table = read_tsv("../data/meta_gene_table.tsv")

```

```{r}
# Get the number of missing values
missing_values <- meta_gene_table |>
  summarise(across(everything(), ~ sum(is.na(.))))
```

```{r}
# Checking if some columns have missing values
missing_values_t <- missing_values |>
  t() |>
  as.data.frame()
colnames(missing_values_t) = c("Missing_values")
missing_values_t |>
  filter(
    Missing_values != 0
  )
```

```{r}
# Drop Columns 'Tissue' and 'Patient_id'
# Tissue: all rows are 'Skin', hence does not provide information
# Patient_id: The same information as 'Sample'

meta_gene_table <- meta_gene_table |> 
  select(!c('Tissue','Patient_id'))
```

```{r}
# Remove genes that have 0 expression (observed when analysing expression significance)

meta_cols <- c('Sample',
               'Tissue_type',
               'Gender',
               'Race',
               'Smoker',
               'Age',
               'BMI')
gene_cols <- meta_gene_table |> 
  select(-one_of(meta_cols)) |> 
  colnames()

# get genes names that have 0 expression
non_zero_expression_genes <- meta_gene_table |>
  pivot_longer(all_of(gene_cols)) |> 
  group_by(name) |> 
  summarise(sum = sum(value)) |> 
  filter(sum != 0) |> 
  ungroup() |> 
  pivot_wider(names_from = name, values_from = sum) |> 
  colnames()
  
```
```{r}
# select non 0 expression genes from the data
meta_gene_table <- meta_gene_table |> 
  select(all_of(non_zero_expression_genes))
```


```{r}
# We save the cleaned data frame
write_tsv(meta_gene_table, file = "../data/cleaned_meta_gene_table.tsv")
```
