---
title: "03_annotation"
format: html
editor: visual
---

```{r}
# output: FALSE
library(tidyverse)
library(clusterProfiler)
library(AnnotationDbi)
library(org.Hs.eg.db)
```

```{r}
# Load data for annotation
expression_data <- read_tsv(gzfile("../data/cleaned_meta_gene_table.tsv.gz"))
```

## Annotation of genes

```{r}
# Find the corresponding gene SYMBOL for all ENSEMBL in org.HS.eg.db 
mapping <- AnnotationDbi::select(org.Hs.eg.db, 
                                 keys = keys(org.Hs.eg.db, keytype = "ENSEMBL"),
                                 keytype = "ENSEMBL",
                                 columns = c("SYMBOL",
                                       "GENENAME",
                                       "CHR"
                                       )
                           ) |> 
                  as.data.frame()

# Use left_join from tidyverse
annotated_data <- 
  expression_data |> 
  left_join(mapping, by = c('gene' = 'ENSEMBL'))

```

```{r}
# 32 genes do not have annotations, we will just remove those genes

no_annotation_genes <- 
  annotated_data |> 
  filter(is.na(SYMBOL)) 

annotated_data <- 
  annotated_data |> 
  anti_join(no_annotation_genes, by = 'gene')
```

```{r}
# 3 genes have multiple annotations. We here delete those genes from our data, 
# as it is difficult to say which annotation is more correct

duplicates <- 
  annotated_data |> 
  group_by(gene) |> 
  filter(n() > 20) 

mult_annotated_genes <- 
  duplicates |>
  dplyr::select(gene, SYMBOL, GENENAME) |> 
  distinct() |> 
  ungroup() 


annotated_data <- 
  annotated_data |> 
  anti_join(mult_annotated_genes, by = 'gene') 
```

```{r}
# save the final annotated gene expression data
write_tsv(annotated_data, gzfile('../data/annotated_meta_gene_table.tsv.gz'))
```
