---
title: "03_augment"
format: html
editor: visual
---

```{r}
# Output: FALSE
library(tidyverse)
library(broom)
```

```{r}
# Output: FALSE
# Loading the clean dataset
data = read_tsv("../data/cleaned_meta_gene_table.tsv")
```

## Standardize gene expression values

```{r}
# lists of meta data columns and gene columns
meta_cols <- c('Sample',
               'Gender',
               'Race',
               'Smoker',
               'Age',
               'BMI')

gene_cols <- data |> 
  select(-one_of(meta_cols)) |> 
  colnames()
```

```{r}
# group expression by genes and scale to 0 mean and 1 st. dev.

aug_data <- data |>
  group_by(gene) |> 
  mutate(std_Lesion = 
           (Lesion - mean(Lesion))/sd(Lesion)) |> 
  mutate(std_Perilesion = 
           (Perilesion - mean(Perilesion))/sd(Perilesion)) |> 
  mutate(log2_Lesion = 
           if_else(Lesion == 0, 
                   0, 
                   log2(Lesion)
                   )
         ) |> 
   ungroup() |> 
   mutate(log2_Perilesion = 
           if_else(Perilesion == 0, 
                   0, 
                   log2(Perilesion)
                   )
         ) |> 
   mutate(log2_expr_change = 
           if_else(expr_diff == 0, 
                   0, 
                   log2(expr_diff)
                   )
         ) 

# Test for standarization. Delete Later

aug_data |> 
  arrange(desc(Perilesion)) |> 
  head(10) |> 
  select(gene ,Lesion, Perilesion)

top_lesion <- 
  aug_data |> 
  filter(Perilesion == 762761) |> 
  pull(gene)

aug_data |>
  filter(gene == top_lesion) |> 
  summarize(mean_p = mean(Perilesion), 
            std_p = sd(Perilesion),
            mean_l = mean(Lesion),
            std_l = sd(Perilesion),
            max_p = max(Perilesion),
            max_l = max(Lesion)) 

(762761-440032)/152882.1

```

```{r}
# We save the augmented data frame
write_tsv(aug_data, 
          file = "../data/augmented_meta_gene_table.tsv")
```
