---
title: "Read_count_analysis"
format: html
editor: visual
---

```{r}
library(tidyverse)
```

```{r}
raw_data <- read_tsv(gzfile('../data/meta_gene_table.tsv.gz'))
```

## Count for each sample

**Missing make levels**

```{r}
gene_cols <- 
  raw_data |> 
  dplyr::select(starts_with('ENSG')) |> 
  colnames()
  

Sample_count <- 
  raw_data |> 
  pivot_longer(gene_cols, 
               names_to = 'Gene', 
               values_to = 'Expression') |> 
  group_by(Sample) |> 
  summarise(Read_count = sum(Expression)) |> 
  mutate(Sample = factor(Sample, 
                         levels = c("1L", "1N",
                                    "2L", "2N",
                                    "3L", "3N",
                                    "4L", "4N",
                                    "5L", "5N",
                                    "6L", "6N",
                                    "7L", "7N",
                                    "8L", "8N",
                                    "9L", "9N",
                                    "10L", "10N", 
                                    "11L", "11N", 
                                    "12L", "12N", 
                                    "13L", "13N", 
                                    "14L", "14N",
                                    "15L", "15N",
                                    "16L", "16N",
                                    "17L", "17N",
                                    "18L", "18N",
                                    "19L", "19N",
                                    "20L", "20N",
                                    "21L", "21N",
                                    "22L", "22N")
         ))


reads <- Sample_count |> 
  ggplot(aes(x = fct_rev(Sample), y = Read_count, fill = Sample)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  labs(title = 'Number of Reads in Each Sample',
       x = 'Sample',
       y = 'Number of reads') +
  theme_minimal() +
  theme(plot.title = element_text(vjust = 2,
                                  hjust = 0.5,
                                  face = 'bold'),
        panel.border = element_rect(colour = "black", 
                                    fill = 'transparent',
                                    size = 0.5),
        legend.position = 'none')

ggsave(filename = "Read_count_raw.png", reads, path = "../pictures", bg = "white")
```

```{r}
augmented_data <- read_tsv('../data/augmented_meta_gene_table.tsv.gz')
```

```{r}
augmented_counts <- 
  augmented_data |> 
  pivot_longer(c(Lesion, Perilesion), 
               names_to = 'Tissue_type', 
               values_to = 'expr') |> 
  mutate(Sample = ifelse(Tissue_type == 'Lesion', 
                        str_c(Sample, 'L'), 
                        str_c(Sample, 'N')
                        )) |> 
  group_by(Sample) |> 
  summarise(Read_count = sum(expr)) |> 
  mutate(Sample = factor(Sample, 
                         levels = c("1L", "1N",
                                    "2L", "2N",
                                    "3L", "3N",
                                    "4L", "4N",
                                    "5L", "5N",
                                    "6L", "6N",
                                    "7L", "7N",
                                    "8L", "8N",
                                    "9L", "9N",
                                    "10L", "10N", 
                                    "11L", "11N", 
                                    "12L", "12N", 
                                    "13L", "13N", 
                                    "14L", "14N",
                                    "15L", "15N",
                                    "16L", "16N",
                                    "17L", "17N",
                                    "18L", "18N",
                                    "19L", "19N",
                                    "20L", "20N",
                                    "21L", "21N",
                                    "22L", "22N")))
  
reads_sig <- augmented_counts |> 
  ggplot(aes(x = fct_rev(Sample), y = Read_count, fill = Sample)) +
  geom_bar(stat = 'identity') +
  coord_flip() +
  labs(title = 'Number of Significant gene reads in Each Sample',
       x = 'Sample',
       y = 'Number of reads') +
  theme_minimal() +
  theme(plot.title = element_text(vjust = 2,
                                  hjust = 0.5,
                                  face = 'bold'),
        panel.border = element_rect(colour = "black", 
                                    fill = 'transparent',
                                    size = 0.5),
        legend.position = 'none')

ggsave("Read_count_significant.png", reads_sig, path = "../pictures", bg = "white")

```
